FROM golang:1.25-alpine

RUN apk add --no-cache git bash kubectl aws-cli

WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o /usr/local/bin/mgtt ./cmd/mgtt

ENTRYPOINT ["mgtt"]
